sudo: false
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - google-chrome --version
  - wget https://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /tmp
  - export PATH=$PATH:/tmp
  - echo $DISPLAY
  - gem update
  - gem install bundler
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install robotframework
  - pip install robotframework-selenium2library
  - ls robottests/ChromeProfiles/zh-cn/Default/


before_script:

rvm:
  - 2.1

python:
  - 2.7
